name: Go
on:
  push:
    branches:
      - "**"
    tags:
      - v*
    paths:
      - "**.go"
      - ".goreleaser.yml"
      - ".golangci.yml"
      - ".dockerignore"
      - "Justfile"
      - "go.*"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "**.go"
      - ".goreleaser.yml"
      - ".golangci.yml"
      - ".dockerignore"
      - "Justfile"
      - "go.*"
      - ".github/workflows/go.yml"

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=2m
          only-new-issues: false
          working-directory: .

  tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.23.x
    env:
      OS: ubuntu-latest
      GOLANG: ${{ matrix.golang }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.golang }}-v1-
      - uses: extractions/setup-just@v2
      - name: Check go.mod and go.sum
        run: |
          go mod tidy -v
          git --no-pager diff go.mod go.sum
          git --no-pager diff --quiet go.mod go.sum
      - name: Run tests on Unix-like operating systems
        run: just test
      - name: Run build
        run: just build
